language: node_js

node_js:
  - 0.10

install:
  - 'npm install'

before_script:

script:
  - 'npm run build:dev'

after_script:
- git add --a \
  && git commit -m 'auto push' \

deploy:  
 provider: azure_web_apps
 skip_cleanup: true
 verbose: true
 